apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-ha
  namespace: app
spec:
  instances: 1   # generic, will patch per overlay
  imageName: "ghcr.io/cloudnative-pg/postgresql:18-system-trixie"
  monitoring:
    enablePodMonitor: false   
    tls:
      enabled: true           
  affinity:
    enablePodAntiAffinity: true
    topologyKey: "kubernetes.io/hostname"
  postgresql:
    parameters:
      synchronous_commit: "on"
  storage:
    size: 10Gi
    storageClass: gp3
    resizeInUseVolumes: true
  backup:
    barmanObjectStore:
      destinationPath: s3://your-bucket/base-backup
      s3Credentials:
        region:
          name: pgbackrest-secret
          key: region
        accessKeyId:
          name: pgbackrest-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: pgbackrest-secret
          key: AWS_SECRET_ACCESS_KEY

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-cluster-ha-every-15m
  namespace: app
spec:
  schedule: "*/5 * * * *"
  backupOwnerReference: self
  cluster:
    name: pg-cluster-ha

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pg-cluster-ha-manual
  namespace: app
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: pg-cluster-ha
  podMetricsEndpoints:
    - port: metrics
      scheme: https
      interval: 15s
      tlsConfig:
        ca:
          secret:
            name: pg-cluster-ha-ca
            key: ca.crt
        serverName: pg-cluster-ha-rw